### ISSUE TITLE
Belum ada dokumentasi + hasil eksekusi

### ISSUE THREAD

**Issue by ceefour** [csh3l3-2017b/0a-heroes-yogiwisesa#1]
@yogiwisesa Nilainya belum maksimal karena di notebooknya belum ada dokumentasi masing-masing subprogram.
Biar maksimal boleh dilengkapi ya :)

**Comment by yogiw** [comment]
Hasil eksekusi  ada di prediction.csv pak. dokumentasi akan saya buat. terima kasih banyak pak

**Comment by ceefour** [comment]
@yogiwisesa , BTW, karena formatnya Notebook, sebaiknya dokumentasinya dalam bentuk sel Markdown di Notebook tersebut, bukan sebagai Python comments

**Comment by yogiw** [comment]
Baik pak, saya revisi lagi, tadi ga ketemu caranya gimana hehehe

**Comment by yogiw** [comment]
Sudah di update dengan ditambahkan markdown di jupyter notebooknya. terima kasih pak

**Comment by ceefour** [comment]
👍 

next time, dokumentasinya per subprogram ya, maksudnya, dokumentasi, trus snippet, dokumentasi lg, trus snippet.. dst.

Contoh struktur notebook yg bagus: https://www.kaggle.com/startupsci/titanic-data-science-solutions
